/*
 * Retroalimentacion del piloto de Vivace Suite.
 *
 * MIGRACION NO EJECUTADA.
 * La escritura y lectura se realizan exclusivamente mediante RPC seguras.
 */

BEGIN;

CREATE TABLE public.pilot_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  member_id bigint NULL REFERENCES public.members(id) ON DELETE SET NULL,
  category text NOT NULL,
  message text NOT NULL,
  page_path text NULL,
  app_version text NULL,
  user_agent text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pilot_feedback_category_check
    CHECK (category IN ('error', 'suggestion', 'question', 'praise')),
  CONSTRAINT pilot_feedback_message_length_check
    CHECK (char_length(btrim(message)) BETWEEN 10 AND 2000),
  CONSTRAINT pilot_feedback_page_path_length_check
    CHECK (page_path IS NULL OR char_length(page_path) <= 500),
  CONSTRAINT pilot_feedback_app_version_length_check
    CHECK (app_version IS NULL OR char_length(app_version) <= 100),
  CONSTRAINT pilot_feedback_user_agent_length_check
    CHECK (user_agent IS NULL OR char_length(user_agent) <= 1000)
);

CREATE INDEX pilot_feedback_created_at_idx
  ON public.pilot_feedback (created_at DESC);

CREATE INDEX pilot_feedback_category_created_at_idx
  ON public.pilot_feedback (category, created_at DESC);

CREATE INDEX pilot_feedback_auth_user_id_idx
  ON public.pilot_feedback (auth_user_id);

CREATE INDEX pilot_feedback_member_id_idx
  ON public.pilot_feedback (member_id)
  WHERE member_id IS NOT NULL;

ALTER TABLE public.pilot_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pilot_feedback FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.pilot_feedback
FROM PUBLIC, anon, authenticated;

REVOKE ALL ON SEQUENCE public.pilot_feedback_id_seq
FROM PUBLIC, anon, authenticated;

CREATE FUNCTION public.submit_pilot_feedback(
  p_category text,
  p_message text,
  p_page_path text DEFAULT NULL,
  p_app_version text DEFAULT NULL,
  p_user_agent text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  current_user_id uuid := auth.uid();
  matching_member_count bigint;
  current_member_id bigint;
  feedback_id bigint;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'authentication_required' USING ERRCODE = '42501';
  END IF;

  IF NOT public.current_member_is_active() THEN
    RAISE EXCEPTION 'active_member_required' USING ERRCODE = '42501';
  END IF;

  SELECT count(*), min(members.id)
  INTO matching_member_count, current_member_id
  FROM public.members AS members
  WHERE members.auth_user_id = current_user_id;

  IF matching_member_count <> 1 THEN
    RAISE EXCEPTION 'member_unavailable' USING ERRCODE = '42501';
  END IF;

  IF p_category IS NULL
    OR btrim(p_category) NOT IN ('error', 'suggestion', 'question', 'praise')
  THEN
    RAISE EXCEPTION 'invalid_category' USING ERRCODE = '22023';
  END IF;

  IF p_message IS NULL
    OR char_length(btrim(p_message)) NOT BETWEEN 10 AND 2000
  THEN
    RAISE EXCEPTION 'invalid_message' USING ERRCODE = '22023';
  END IF;

  IF char_length(COALESCE(p_page_path, '')) > 500
    OR char_length(COALESCE(p_app_version, '')) > 100
    OR char_length(COALESCE(p_user_agent, '')) > 1000
  THEN
    RAISE EXCEPTION 'invalid_context' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.pilot_feedback (
    auth_user_id,
    member_id,
    category,
    message,
    page_path,
    app_version,
    user_agent
  ) VALUES (
    current_user_id,
    current_member_id,
    btrim(p_category),
    btrim(p_message),
    NULLIF(btrim(p_page_path), ''),
    NULLIF(btrim(p_app_version), ''),
    NULLIF(btrim(p_user_agent), '')
  )
  RETURNING id INTO feedback_id;

  RETURN feedback_id;
END;
$function$;

CREATE FUNCTION public.list_pilot_feedback(
  p_category text DEFAULT NULL,
  p_limit integer DEFAULT 100
)
RETURNS TABLE (
  id bigint,
  member_name text,
  category text,
  message text,
  page_path text,
  app_version text,
  user_agent text,
  created_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.has_app_permission('settings.manage') THEN
    RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501';
  END IF;

  IF p_category IS NOT NULL
    AND btrim(p_category) NOT IN ('error', 'suggestion', 'question', 'praise')
  THEN
    RAISE EXCEPTION 'invalid_category' USING ERRCODE = '22023';
  END IF;

  RETURN QUERY
  SELECT
    feedback.id,
    COALESCE(
      NULLIF(btrim(concat_ws(' ', members.name, members.last_name)), ''),
      'Usuario sin perfil'
    ),
    feedback.category,
    feedback.message,
    feedback.page_path,
    feedback.app_version,
    feedback.user_agent,
    feedback.created_at
  FROM public.pilot_feedback AS feedback
  LEFT JOIN public.members AS members
    ON members.id = feedback.member_id
  WHERE p_category IS NULL OR feedback.category = btrim(p_category)
  ORDER BY feedback.created_at DESC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 100), 1), 200);
END;
$function$;

CREATE FUNCTION public.get_pilot_feedback_summary()
RETURNS TABLE (
  total_count bigint,
  error_count bigint,
  suggestion_count bigint,
  question_count bigint,
  praise_count bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.has_app_permission('settings.manage') THEN
    RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    count(*),
    count(*) FILTER (WHERE feedback.category = 'error'),
    count(*) FILTER (WHERE feedback.category = 'suggestion'),
    count(*) FILTER (WHERE feedback.category = 'question'),
    count(*) FILTER (WHERE feedback.category = 'praise')
  FROM public.pilot_feedback AS feedback;
END;
$function$;

ALTER FUNCTION public.submit_pilot_feedback(text, text, text, text, text)
  OWNER TO postgres;
ALTER FUNCTION public.list_pilot_feedback(text, integer)
  OWNER TO postgres;
ALTER FUNCTION public.get_pilot_feedback_summary()
  OWNER TO postgres;

REVOKE ALL ON FUNCTION public.submit_pilot_feedback(text, text, text, text, text)
FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.list_pilot_feedback(text, integer)
FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_pilot_feedback_summary()
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.submit_pilot_feedback(text, text, text, text, text)
TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_pilot_feedback(text, integer)
TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pilot_feedback_summary()
TO authenticated;

COMMENT ON TABLE public.pilot_feedback IS
  'Retroalimentacion contextual enviada por usuarios durante el piloto de Vivace Suite.';
COMMENT ON FUNCTION public.submit_pilot_feedback(text, text, text, text, text) IS
  'Registra retroalimentacion para el usuario autenticado resolviendo su integrante en el servidor.';
COMMENT ON FUNCTION public.list_pilot_feedback(text, integer) IS
  'Lista retroalimentacion sin exponer UUID de autenticacion; requiere settings.manage.';
COMMENT ON FUNCTION public.get_pilot_feedback_summary() IS
  'Resume la retroalimentacion del piloto; requiere settings.manage.';

COMMIT;

/*
 * ROLLBACK MANUAL (revisar antes de ejecutar):
 * BEGIN;
 * DROP FUNCTION IF EXISTS public.get_pilot_feedback_summary();
 * DROP FUNCTION IF EXISTS public.list_pilot_feedback(text, integer);
 * DROP FUNCTION IF EXISTS public.submit_pilot_feedback(text, text, text, text, text);
 * DROP TABLE IF EXISTS public.pilot_feedback;
 * COMMIT;
 */
