/* Registro temporal grupal. MIGRACION LOCAL NO EJECUTADA. */

BEGIN;

DO $precondition$
BEGIN
  IF pg_catalog.to_regclass('public.intake_windows') IS NOT NULL
    OR pg_catalog.to_regclass('public.intake_requests') IS NOT NULL
  THEN
    RAISE EXCEPTION 'Las tablas intake ya existen; revisar antes de aplicar.';
  END IF;

  IF pg_catalog.to_regprocedure(
    'public.create_student_invitation(bigint,interval)'
  ) IS NULL THEN
    RAISE EXCEPTION 'Falta create_student_invitation(bigint,interval).';
  END IF;

  IF pg_catalog.to_regprocedure('public.consume_student_invitation(text)') IS NULL
    OR pg_catalog.to_regclass('public.student_account_invitations') IS NULL
  THEN
    RAISE EXCEPTION 'Falta el contrato completo de invitaciones individuales.';
  END IF;

  IF pg_catalog.to_regprocedure('extensions.gen_random_bytes(integer)') IS NULL
    OR pg_catalog.to_regprocedure('extensions.digest(bytea,text)') IS NULL
    OR pg_catalog.to_regprocedure('extensions.digest(text,text)') IS NULL
    OR pg_catalog.to_regprocedure('pg_catalog.gen_random_uuid()') IS NULL
  THEN
    RAISE EXCEPTION 'Faltan dependencias criptograficas requeridas.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_attribute AS attributes
    WHERE attributes.attrelid = 'public.student_account_invitations'::regclass
      AND attributes.attname = 'id'
      AND attributes.atttypid = 'uuid'::regtype
      AND attributes.attnotnull AND NOT attributes.attisdropped
  ) THEN
    RAISE EXCEPTION 'student_account_invitations.id no cumple el contrato uuid.';
  END IF;
END;
$precondition$;

CREATE TABLE public.intake_windows (
  id uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid(),
  name text NOT NULL,
  public_token_hash text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'open',
  expires_at timestamptz NOT NULL,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz NULL,
  message text NULL,
  CONSTRAINT intake_windows_name_check
    CHECK (char_length(btrim(name)) BETWEEN 3 AND 120),
  CONSTRAINT intake_windows_token_hash_check
    CHECK (public_token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT intake_windows_status_check
    CHECK (status IN ('open', 'closed', 'expired', 'revoked')),
  CONSTRAINT intake_windows_message_check
    CHECK (message IS NULL OR char_length(btrim(message)) BETWEEN 1 AND 500),
  CONSTRAINT intake_windows_closed_state_check
    CHECK ((status = 'open' AND closed_at IS NULL) OR (status <> 'open' AND closed_at IS NOT NULL))
);

CREATE TABLE public.intake_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intake_window_id uuid NOT NULL REFERENCES public.intake_windows(id) ON DELETE CASCADE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text NULL,
  requested_voice text NULL,
  requested_role text NOT NULL DEFAULT 'student',
  notes text NULL,
  status text NOT NULL DEFAULT 'pending',
  reviewed_by uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at timestamptz NULL,
  rejection_reason text NULL,
  member_id bigint NULL REFERENCES public.members(id) ON DELETE SET NULL,
  invitation_id uuid NULL REFERENCES public.student_account_invitations(id) ON DELETE SET NULL,
  invitation_delivery_status text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT intake_requests_first_name_check
    CHECK (char_length(btrim(first_name)) BETWEEN 1 AND 100),
  CONSTRAINT intake_requests_last_name_check
    CHECK (char_length(btrim(last_name)) BETWEEN 1 AND 150),
  CONSTRAINT intake_requests_email_check
    CHECK (
      email = lower(btrim(email))
      AND char_length(email) BETWEEN 3 AND 320
      AND email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    ),
  CONSTRAINT intake_requests_phone_check
    CHECK (phone IS NULL OR char_length(btrim(phone)) BETWEEN 7 AND 30),
  CONSTRAINT intake_requests_voice_check
    CHECK (requested_voice IS NULL OR requested_voice IN ('Soprano', 'Contralto', 'Tenor', 'Bajo', 'Otra')),
  CONSTRAINT intake_requests_requested_role_check
    CHECK (requested_role IN ('student', 'member')),
  CONSTRAINT intake_requests_notes_check
    CHECK (notes IS NULL OR char_length(btrim(notes)) BETWEEN 1 AND 1000),
  CONSTRAINT intake_requests_status_check
    CHECK (status IN ('pending', 'approved', 'rejected')),
  CONSTRAINT intake_requests_rejection_check
    CHECK (
      (status = 'rejected' AND rejection_reason IS NOT NULL AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)
      OR (status <> 'rejected' AND rejection_reason IS NULL)
    ),
  CONSTRAINT intake_requests_approval_check
    CHECK (
      status <> 'approved'
      OR (member_id IS NOT NULL AND invitation_id IS NOT NULL AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)
    ),
  CONSTRAINT intake_requests_delivery_check
    CHECK (invitation_delivery_status IS NULL OR invitation_delivery_status IN ('manual_pending', 'sent'))
);

CREATE UNIQUE INDEX intake_requests_pending_email_unique
  ON public.intake_requests (intake_window_id, lower(email))
  WHERE status = 'pending';
CREATE INDEX intake_windows_created_at_idx
  ON public.intake_windows (created_at DESC);
CREATE INDEX intake_windows_status_expires_at_idx
  ON public.intake_windows (status, expires_at);
CREATE INDEX intake_requests_status_created_at_idx
  ON public.intake_requests (status, created_at DESC);
CREATE INDEX intake_requests_window_created_at_idx
  ON public.intake_requests (intake_window_id, created_at DESC);

ALTER TABLE public.intake_windows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_windows FORCE ROW LEVEL SECURITY;
ALTER TABLE public.intake_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_requests FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.intake_windows, public.intake_requests
FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.intake_requests_id_seq
FROM PUBLIC, anon, authenticated;

CREATE FUNCTION public.create_intake_window(
  p_name text,
  p_valid_for_hours integer,
  p_message text DEFAULT NULL
)
RETURNS TABLE (
  window_id uuid,
  window_name text,
  expires_at timestamptz,
  plain_token text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  current_user_id uuid := auth.uid();
  created_window public.intake_windows%ROWTYPE;
BEGIN
  IF current_user_id IS NULL OR NOT (
    public.has_app_permission('members.manage')
    OR public.has_app_permission('roles.manage')
  ) THEN
    RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501';
  END IF;

  IF p_name IS NULL OR char_length(btrim(p_name)) NOT BETWEEN 3 AND 120
    OR p_valid_for_hours NOT IN (2, 4, 8, 24, 48)
    OR char_length(COALESCE(btrim(p_message), '')) > 500
  THEN
    RAISE EXCEPTION 'invalid_window' USING ERRCODE = '22023';
  END IF;

  plain_token := translate(
    rtrim(encode(extensions.gen_random_bytes(32), 'base64'), '='),
    '+/', '-_'
  );

  INSERT INTO public.intake_windows (
    name, public_token_hash, expires_at, created_by, message
  ) VALUES (
    btrim(p_name),
    encode(extensions.digest(plain_token, 'sha256'), 'hex'),
    now() + pg_catalog.make_interval(hours => p_valid_for_hours),
    current_user_id,
    NULLIF(btrim(p_message), '')
  ) RETURNING * INTO created_window;

  RETURN QUERY SELECT
    created_window.id,
    created_window.name,
    created_window.expires_at,
    plain_token;
END;
$function$;

CREATE FUNCTION public.validate_intake_window(p_plain_token text)
RETURNS TABLE (
  is_available boolean,
  result_code text,
  window_name text,
  window_message text,
  expires_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  target_window public.intake_windows%ROWTYPE;
BEGIN
  IF p_plain_token IS NULL OR char_length(btrim(p_plain_token)) < 32 THEN
    RETURN QUERY SELECT false, 'invalid', NULL::text, NULL::text, NULL::timestamptz;
    RETURN;
  END IF;

  SELECT windows.* INTO target_window
  FROM public.intake_windows AS windows
  WHERE windows.public_token_hash = encode(
    extensions.digest(btrim(p_plain_token), 'sha256'), 'hex'
  ) LIMIT 1;

  IF NOT FOUND THEN
    RETURN QUERY SELECT false, 'invalid', NULL::text, NULL::text, NULL::timestamptz;
  ELSIF target_window.status <> 'open' THEN
    RETURN QUERY SELECT false, target_window.status, target_window.name, target_window.message, target_window.expires_at;
  ELSIF target_window.expires_at <= now() THEN
    RETURN QUERY SELECT false, 'expired', target_window.name, target_window.message, target_window.expires_at;
  ELSE
    RETURN QUERY SELECT true, 'open', target_window.name, target_window.message, target_window.expires_at;
  END IF;
END;
$function$;

CREATE FUNCTION public.submit_intake_request(
  p_plain_token text,
  p_first_name text,
  p_last_name text,
  p_email text,
  p_phone text DEFAULT NULL,
  p_requested_voice text DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS TABLE (success boolean, result_code text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  target_window public.intake_windows%ROWTYPE;
  normalized_email text := lower(btrim(p_email));
BEGIN
  SELECT windows.* INTO target_window
  FROM public.intake_windows AS windows
  WHERE windows.public_token_hash = encode(
    extensions.digest(COALESCE(btrim(p_plain_token), ''), 'sha256'), 'hex'
  ) FOR UPDATE;

  IF NOT FOUND OR target_window.status <> 'open' OR target_window.expires_at <= now() THEN
    RETURN QUERY SELECT false, 'window_unavailable';
    RETURN;
  END IF;

  IF p_first_name IS NULL OR char_length(btrim(p_first_name)) NOT BETWEEN 1 AND 100
    OR p_last_name IS NULL OR char_length(btrim(p_last_name)) NOT BETWEEN 1 AND 150
    OR normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    OR char_length(normalized_email) > 320
    OR (
      NULLIF(btrim(p_phone), '') IS NOT NULL
      AND char_length(btrim(p_phone)) NOT BETWEEN 7 AND 30
    )
    OR char_length(COALESCE(btrim(p_notes), '')) > 1000
    OR (p_requested_voice IS NOT NULL AND btrim(p_requested_voice) NOT IN ('Soprano', 'Contralto', 'Tenor', 'Bajo', 'Otra'))
  THEN
    RETURN QUERY SELECT false, 'invalid_data';
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.intake_requests AS requests
    WHERE requests.intake_window_id = target_window.id
      AND requests.email = normalized_email
      AND requests.status = 'pending'
  ) THEN
    RETURN QUERY SELECT false, 'duplicate_pending';
    RETURN;
  END IF;

  INSERT INTO public.intake_requests (
    intake_window_id, first_name, last_name, email, phone,
    requested_voice, requested_role, notes
  ) VALUES (
    target_window.id, btrim(p_first_name), btrim(p_last_name),
    normalized_email, NULLIF(btrim(p_phone), ''),
    NULLIF(btrim(p_requested_voice), ''), 'student', NULLIF(btrim(p_notes), '')
  );

  RETURN QUERY SELECT true, 'submitted';
EXCEPTION WHEN unique_violation THEN
  RETURN QUERY SELECT false, 'duplicate_pending';
END;
$function$;

CREATE FUNCTION public.list_intake_windows()
RETURNS TABLE (
  id uuid, name text, status text, expires_at timestamptz,
  created_at timestamptz, closed_at timestamptz, message text,
  pending_count bigint
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$
BEGIN
  IF auth.uid() IS NULL OR NOT (
    public.has_app_permission('members.manage') OR public.has_app_permission('roles.manage')
  ) THEN RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501'; END IF;

  RETURN QUERY SELECT
    windows.id, windows.name,
    CASE WHEN windows.status = 'open' AND windows.expires_at <= now()
      THEN 'expired' ELSE windows.status END,
    windows.expires_at, windows.created_at, windows.closed_at, windows.message,
    count(requests.id) FILTER (WHERE requests.status = 'pending')
  FROM public.intake_windows AS windows
  LEFT JOIN public.intake_requests AS requests ON requests.intake_window_id = windows.id
  GROUP BY windows.id ORDER BY windows.created_at DESC LIMIT 100;
END;
$function$;

CREATE FUNCTION public.close_or_revoke_intake_window(
  p_window_id uuid,
  p_action text
)
RETURNS TABLE (success boolean, result_code text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $function$
BEGIN
  IF auth.uid() IS NULL OR NOT (
    public.has_app_permission('members.manage') OR public.has_app_permission('roles.manage')
  ) THEN RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501'; END IF;
  IF p_action NOT IN ('closed', 'revoked') THEN
    RAISE EXCEPTION 'invalid_action' USING ERRCODE = '22023';
  END IF;

  UPDATE public.intake_windows AS windows
  SET status = p_action, closed_at = now()
  WHERE windows.id = p_window_id AND windows.status = 'open';

  IF FOUND THEN RETURN QUERY SELECT true, p_action;
  ELSE RETURN QUERY SELECT false, 'not_open'; END IF;
END;
$function$;

CREATE FUNCTION public.list_intake_requests(p_status text DEFAULT NULL)
RETURNS TABLE (
  id bigint, window_id uuid, window_name text, first_name text,
  last_name text, email text, phone text, requested_voice text, requested_role text,
  notes text, status text, rejection_reason text, member_id bigint,
  invitation_id uuid, invitation_delivery_status text, created_at timestamptz,
  reviewed_at timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$
BEGIN
  IF auth.uid() IS NULL OR NOT (
    public.has_app_permission('members.manage') OR public.has_app_permission('roles.manage')
  ) THEN RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501'; END IF;
  IF p_status IS NOT NULL AND p_status NOT IN ('pending', 'approved', 'rejected') THEN
    RAISE EXCEPTION 'invalid_status' USING ERRCODE = '22023';
  END IF;

  RETURN QUERY SELECT
    requests.id, windows.id, windows.name, requests.first_name,
    requests.last_name, requests.email, requests.phone,
    requests.requested_voice, requests.requested_role, requests.notes, requests.status,
    requests.rejection_reason, requests.member_id, requests.invitation_id,
    requests.invitation_delivery_status, requests.created_at, requests.reviewed_at
  FROM public.intake_requests AS requests
  JOIN public.intake_windows AS windows ON windows.id = requests.intake_window_id
  WHERE p_status IS NULL OR requests.status = p_status
  ORDER BY requests.created_at DESC LIMIT 200;
END;
$function$;

CREATE FUNCTION public.approve_intake_request(
  p_request_id bigint,
  p_approved_role text DEFAULT NULL
)
RETURNS TABLE (
  request_id bigint, member_id bigint, member_resolution text,
  invitation_id uuid, invitation_expires_at timestamptz,
  plain_invitation_token text, delivery_status text
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $function$
DECLARE
  current_user_id uuid := auth.uid();
  target_request public.intake_requests%ROWTYPE;
  matching_member public.members%ROWTYPE;
  matching_member_id bigint;
  member_count bigint;
  auth_count bigint;
  created_invitation record;
  resolution text;
  effective_role text;
  invitation_valid_for constant interval := interval '7 days';
BEGIN
  IF current_user_id IS NULL OR NOT (
    public.has_app_permission('members.manage') OR public.has_app_permission('roles.manage')
  ) THEN RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501'; END IF;

  SELECT requests.* INTO target_request
  FROM public.intake_requests AS requests
  WHERE requests.id = p_request_id FOR UPDATE;
  IF NOT FOUND OR target_request.status <> 'pending' THEN
    RAISE EXCEPTION 'request_not_pending' USING ERRCODE = 'P0001';
  END IF;

  effective_role := COALESCE(NULLIF(btrim(p_approved_role), ''), target_request.requested_role);
  IF effective_role NOT IN ('student', 'member') THEN
    RAISE EXCEPTION 'invalid_approved_role' USING ERRCODE = '22023';
  END IF;

  LOCK TABLE public.members IN SHARE ROW EXCLUSIVE MODE;
  SELECT count(*), min(members.id) INTO member_count, matching_member_id
  FROM public.members AS members
  WHERE lower(btrim(members.email)) = target_request.email;
  IF member_count > 1 THEN RAISE EXCEPTION 'duplicate_members' USING ERRCODE = 'P0001'; END IF;

  IF member_count = 1 THEN
    SELECT members.* INTO matching_member FROM public.members AS members
    WHERE members.id = matching_member_id FOR UPDATE;
    IF matching_member.auth_user_id IS NOT NULL THEN
      RAISE EXCEPTION 'member_already_linked' USING ERRCODE = 'P0001';
    END IF;
    IF lower(btrim(matching_member.status)) <> 'activo'
      OR matching_member.role NOT IN ('member', 'student') THEN
      RAISE EXCEPTION 'member_not_eligible' USING ERRCODE = 'P0001';
    END IF;
    IF matching_member.role <> effective_role THEN
      RAISE EXCEPTION 'member_role_conflict' USING ERRCODE = 'P0001';
    END IF;
    resolution := 'existing';
  ELSE
    SELECT count(*) INTO auth_count FROM auth.users AS users
    WHERE lower(btrim(users.email)) = target_request.email;
    IF auth_count > 0 THEN RAISE EXCEPTION 'auth_account_conflict' USING ERRCODE = 'P0001'; END IF;

    INSERT INTO public.members (
      name, last_name, email, phone, voice, status, role
    ) VALUES (
      target_request.first_name, target_request.last_name,
      target_request.email, target_request.phone,
      COALESCE(target_request.requested_voice, 'Otra'), 'Activo', effective_role
    ) RETURNING * INTO matching_member;
    resolution := 'created';
  END IF;

  SELECT * INTO STRICT created_invitation
  FROM public.create_student_invitation(matching_member.id, invitation_valid_for);

  UPDATE public.intake_requests AS requests SET
    status = 'approved', reviewed_by = current_user_id, reviewed_at = now(),
    member_id = matching_member.id,
    invitation_id = created_invitation.invitation_id,
    invitation_delivery_status = 'manual_pending'
  WHERE requests.id = target_request.id;

  RETURN QUERY SELECT
    target_request.id, matching_member.id, resolution,
    created_invitation.invitation_id, created_invitation.expires_at,
    created_invitation.plain_token, 'manual_pending'::text;
END;
$function$;

CREATE FUNCTION public.reject_intake_request(
  p_request_id bigint,
  p_reason text
)
RETURNS TABLE (success boolean, result_code text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $function$
BEGIN
  IF auth.uid() IS NULL OR NOT (
    public.has_app_permission('members.manage') OR public.has_app_permission('roles.manage')
  ) THEN RAISE EXCEPTION 'permission_denied' USING ERRCODE = '42501'; END IF;
  IF p_reason IS NULL OR char_length(btrim(p_reason)) NOT BETWEEN 3 AND 500 THEN
    RAISE EXCEPTION 'invalid_reason' USING ERRCODE = '22023';
  END IF;

  UPDATE public.intake_requests AS requests SET
    status = 'rejected', reviewed_by = auth.uid(), reviewed_at = now(),
    rejection_reason = btrim(p_reason)
  WHERE requests.id = p_request_id AND requests.status = 'pending';
  IF FOUND THEN RETURN QUERY SELECT true, 'rejected';
  ELSE RETURN QUERY SELECT false, 'not_pending'; END IF;
END;
$function$;

ALTER FUNCTION public.create_intake_window(text,integer,text) OWNER TO postgres;
ALTER FUNCTION public.validate_intake_window(text) OWNER TO postgres;
ALTER FUNCTION public.submit_intake_request(text,text,text,text,text,text,text) OWNER TO postgres;
ALTER FUNCTION public.list_intake_windows() OWNER TO postgres;
ALTER FUNCTION public.close_or_revoke_intake_window(uuid,text) OWNER TO postgres;
ALTER FUNCTION public.list_intake_requests(text) OWNER TO postgres;
ALTER FUNCTION public.approve_intake_request(bigint,text) OWNER TO postgres;
ALTER FUNCTION public.reject_intake_request(bigint,text) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.create_intake_window(text,integer,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.validate_intake_window(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.submit_intake_request(text,text,text,text,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.list_intake_windows() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.close_or_revoke_intake_window(uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.list_intake_requests(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.approve_intake_request(bigint,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reject_intake_request(bigint,text) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.validate_intake_window(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_intake_request(text,text,text,text,text,text,text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_intake_window(text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_intake_windows() TO authenticated;
GRANT EXECUTE ON FUNCTION public.close_or_revoke_intake_window(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_intake_requests(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_intake_request(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_intake_request(bigint,text) TO authenticated;

COMMIT;

/* ROLLBACK MANUAL, REVISAR ANTES DE EJECUTAR:
BEGIN;
DROP FUNCTION IF EXISTS public.reject_intake_request(bigint,text);
DROP FUNCTION IF EXISTS public.approve_intake_request(bigint,text);
DROP FUNCTION IF EXISTS public.list_intake_requests(text);
DROP FUNCTION IF EXISTS public.close_or_revoke_intake_window(uuid,text);
DROP FUNCTION IF EXISTS public.list_intake_windows();
DROP FUNCTION IF EXISTS public.submit_intake_request(text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS public.validate_intake_window(text);
DROP FUNCTION IF EXISTS public.create_intake_window(text,integer,text);
DROP TABLE IF EXISTS public.intake_requests;
DROP TABLE IF EXISTS public.intake_windows;
COMMIT;
*/
